name = "upbot"
main = "src/index.ts" # ဒါမှမဟုတ် မင်းရဲ့ code file path

[[d1_databases]]
binding = "DB"
database_name = "my-db"
database_id = "11285fbc-45a0-4be7-9e12-f642c610b2b2" # Cloudflare D1 က ယူပါ

[[kv_namespaces]]
binding = "KP_PING_CACHE"
id = "198ca39f0e5f4745b97c359cdcbd0fef"